config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  resources :users, :sessions, :books, :shows, :movies, :book_searches, :movie_searches, :tv_searches, :subscriptions
  get 'logout', to: "sessions#destroy"
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/models/book_search.rb
class BookSearch < ActiveRecord::Base

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/models/movie_search.rb
class MovieSearch < ActiveRecord::Base
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :subscriptions
  has_many :users, through: :subscriptions
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/tv_search.rb
class TvSearch < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
	has_many :subscriptions
	has_many :books, through: :subscriptions
	has_many :movies, through: :subscriptions
	has_many :shows, through: :subscriptions

  def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :current_book, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :show, :update, :destroy]

  def index
    if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
    else
      @books = Book.all.order(created_at: :desc)
    end
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @book.update_attributes(book_params)
    redirect_to root_path
  end

  def destroy
    @reviews = Review.where(book_id: @book.id)
    @reviews.each do |review|
      review.destroy
    end
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :image, :publication_date, :publisher, :synopsis)
  end

  def current_book
    @book = Book.find_by_id(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :current_movie, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :show, :update, :destroy]

  def index
    if params[:search]
      @movies = Movie.search(params[:search]).order("created_at DESC")
    else
      @movies = Movie.all.order(created_at: :desc)
    end
  end

  def new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to root_path
  end

  def show

  end

  def edit
  end

  def update
    @movie.update_attributes(movie_params)
    redirect_to root_path
  end

  def destroy
    @reviews = Review.where(movie_id: @movie.id)
    @reviews.each do |review|
      review.destroy
    end
    @movie.destroy
    redirect_to root_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :genre, :image, :cast, :director, :premier, :language, :summary)
  end

  def current_movie
    @movie = Movie.find_by_id(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Succesfully logged in."
      redirect_to root_path
    else
      flash[:error] = "Incorrect email or password."
      redirect_to new_session_path
    end
  end

  def destroy
    logout
    flash[:notice] = "Succesfully logged out."
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  before_action :current_show, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :show, :update, :destroy]

  def index
    if params[:search]
      @shows = Show.search(params[:search]).order("created_at DESC")
    else
      @shows = Show.all.order(created_at: :desc)
    end
  end

  def new
  end

  def create
    @show = Show.new(show_params)
    @show.save
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @show.update_attributes(show_params)
    redirect_to root_path
  end

  def destroy
    @reviews = Review.where(show_id: @show.id)
    @reviews.each do |review|
      review.destroy
    end
    @show.destroy
    redirect_to root_path
  end

  private

  def show_params
    params.require(:show).permit(:title, :genre, :image, :premier, :summary)
  end

  def current_show
    @show = Show.find_by_id(params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in?, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def index
      @books = Book.all
      @shows = Show.all
      @movies = Movie.all
  end

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to root_path
    else
      flash[:error] = "Email has already been taken"
      redirect_to session_new
    end
  end

    def show
      @user = User.find_by_id(params[:id])
      @books = @user.books.order(current: :desc)
    end

  def edit
  end

  def update
    current_params = params.require(:user).permit(:name, :email)
    @user.update_attributes(current_params)
    redirect_to user_path
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_searches_helper.rb
module BookSearchesHelper

  require "net/http"
  require "json"
  require "openssl"
  #OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  SECRET_KEY = Figaro.env.google_books

  def book_url(book_name)
    "https://www.googleapis.com/books/v1/volumes?q=#{book_name}&key=#{SECRET_KEY}"
  end

  def fetch_book_data(book_name)
    uri = URI(book_url(book_name))
    response = Net::HTTP.get(uri)  
  end

  def display_results(book_name)
    @book_data = fetch_book_data(book_name)
  end 
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/movie_searches_helper.rb
module MovieSearchesHelper

  require "net/http"
  require "json"
  require "openssl"
  #OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  SECRET_KEY = Figaro.env.the_movie_db

  def movie_url(movie_name)
    "https://api.themoviedb.org/3/search/movie?api_key=#{SECRET_KEY}&language=en-US&query=#{movie_name}&page=1&include_adult=true"
  end

  def fetch_movie_data(movie_name)
    uri = URI(movie_url(movie_name))
    response = Net::HTTP.get(uri)  
  end

  def display_results(movie_name)
    @movie_data = fetch_movie_data(movie_name)
  end 
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path 
    end
  end

  def logged_out?
    if current_user != nil
      redirect_to user_path(current_user)
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def authorized?(user)
    current_user == user
  end

end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/tv_searches_helper.rb
module TvSearchesHelper

  require "net/http"
  require "json"
  require "openssl"
  #OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  SECRET_KEY = Figaro.env.the_movie_db

  def tv_url(tv_name)
    "https://api.themoviedb.org/3/search/tv?api_key=#{SECRET_KEY}&language=en-US&query=#{tv_name}&page=1"
  end

  def fetch_tv_data(tv_name)
    uri = URI(tv_url(tv_name))
    response = Net::HTTP.get(uri)  
  end

  def display_results(tv_name)
    @tv_data = fetch_tv_data(tv_name)
  end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<ul class="list-group" id="books-list">
  <% @books.each do |book| %>
    <li class="col-md-6">
      <div class="book">
        <%= link_to book do %>
          <img alt="Book Jacket" class="homepageImages" src=<%= book.image %> >
        <% end %>
        <h3><%= link_to book.title, book_path(book.id) %></h3>
        <p><%= book.author %></p>
        <p><b><%= book.genre %></b></p>
      </div>
    </li>
  <% end %>
</ul> 

app/views/books/show.html.erb
<div class="container">
  <h1 class="text-center"><%= @book.title %><h1>
  <h3 class="text-center"><%= @book.author %><h3>
</div>

<ul class="container">
  <img src=<%= @book.image %> alt="Book Jacket" id="showpageImages">
  <p><b>Genre: </b><%= @book.genre %></p>
  <p><b>Publisher: </b><%= @book.publisher %></p>
  <p><b>Publication Date: </b><%= @book.publication_date %></p>
  <p><b>Synopsis: </b><%= @book.synopsis %></p>
</ul>

app/views/shows/index.html.erb
<ul class="list-group" id="shows-list">
  <% @shows.each do |show| %>
    <li class="col-md-6">
      <div class="show">
        <%= link_to show do %>
          <img alt="Book Jacket" class="homepageImages" src=<%= show.image %> >
        <% end %>
        <h3><%= link_to show.title, show_path(show.id) %></h3>
        <p><b><%= show.genre %></b></p>
      </div>
    </li>
  <% end %>
</ul> 

app/views/shows/show.html.erb
<div class="container">
  <h1 class="text-center"><%= @show.title %><h1>
</div>

<ul class="container">
  <img src=<%= @show.image %> alt="Book Jacket" id="showpageImages">
  <p><b>Genre: </b><%= @show.genre %></p>
  <p><b>Premier: </b><%= @show.premier %></p>
  <p><b>Summary: </b><%= @show.summary %></p>
</ul>

app/views/users/index.html.erb
 <div class="container">

  <div class="text-center">
    <h1>Geek Ground</h1>
  </div>

  <div class="container">
    <% if current_user %> 
      <%= link_to "Add Book/Comic", new_book_search_path, class: "btn btn-primary pull-right" %>
      <%= link_to "Add Movie", new_movie_search_path, class: "btn btn-primary pull-right" %>
      <%= link_to "Add TV Show", new_tv_search_path, class: "btn btn-primary pull-right" %>
    <% end %>
  </div>

  <div class="row">

    <div class="col-md-6">

      <div>
        <h3>Discussion Stream</h3>
      </div>

    </div>

    <div class="col-md-6">

      <div>
      Potential React componet example
      <%= react_component "Media", {data: @books}%>
      </div>

      <div>
        <h3><%= link_to "Books", books_path %></h3>
        <% @books.each do |book| %>
          <p><%= book.title %></p>
          <% if current_user%>
            <%= link_to "Follow", controller: "subscriptions", action:"create" ,class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
      <div>
        <h3><%= link_to "TV Shows", shows_path %></h3>
        <% @shows.each do |show| %>
          <p><%= show.title %></p>
        <% end %>
      </div>
      <div>
        <h3><%= link_to "Movies", movies_path %></h3>
        <% @movies.each do |movie| %>
          <p><%= movie.title %></p>
        <% end %>
      </div>

    </div>

  </div>

</div>

app/views/users/new.html.erb
<div class="page">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_for :user, url: users_path do |f| %>
        <fieldset>
          <h1 class="text-center">Sign Up!</h1>

          <div class="form-group">
            <label class="col-md-4 control-label" for="name">Name</label>
            <div class="col-md-8">
              <%= f.text_field :name, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="email">Email</label>
            <div class="col-md-8">
              <%= f.text_field :email, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password">Password</label>
            <div class="col-md-8">
              <%= f.password_field :password, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password_confirmation">Confirm Password</label>
            <div class="col-md-8">
              <%= f.password_field :password_confirmation, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12">
              <%= f.submit "Sign up", class: "btn btn-success" %>
            </div>
          </div>
          
        </fieldset>
      <% end %>

    </div>
  </div>
</div>